@extends('public.layout')
@section('content')
<section class="rounded-3xl bg-slate-950 px-6 py-14 text-white md:px-12"><p class="text-sm font-semibold uppercase tracking-widest text-indigo-300">Besofton Insights</p><h1 class="mt-4 max-w-3xl text-4xl font-extrabold leading-tight md:text-6xl">Ide, panduan, dan pembelajaran teknologi.</h1><p class="mt-5 max-w-2xl text-slate-300">Jelajahi artikel, tutorial, dan materi belajar dari Besofton.</p><form action="{{ route('search') }}" class="mt-8 flex max-w-xl gap-2"><input class="form-input text-slate-900" type="search" name="q" placeholder="Cari topik atau artikel..." aria-label="Cari artikel"><button class="btn-primary">Cari</button></form></section>
@if($featured->isNotEmpty())<section class="mt-12"><h2 class="mb-5 text-2xl font-bold">Pilihan editor</h2><div class="grid gap-5 md:grid-cols-3">@foreach($featured as $post)@include('public.partials.card', ['post'=>$post])@endforeach</div></section>@endif
<section class="mt-12"><h2 class="mb-5 text-2xl font-bold">Artikel terbaru</h2><div class="grid gap-5 md:grid-cols-3">@forelse($posts as $post)@include('public.partials.card', ['post'=>$post])@empty<p class="col-span-3 rounded-xl bg-slate-50 p-8 text-slate-500">Artikel akan segera hadir.</p>@endforelse</div><div class="mt-6">{{ $posts->links() }}</div></section>
@if($topics->isNotEmpty())<section class="mt-12"><h2 class="mb-5 text-2xl font-bold">Jelajahi topik</h2><div class="flex flex-wrap gap-2">@foreach($topics as $topic)<a wire:navigate href="{{ route('topic.show', $topic) }}" class="rounded-full border border-slate-300 px-4 py-2 text-sm hover:border-indigo-600 hover:text-indigo-700">{{ $topic->name }}</a>@endforeach</div></section>@endif
@foreach(['Video' => [$videos, 'video.show'], 'Kuis' => [$quizzes, 'quiz.show'], 'Jalur belajar' => [$paths, 'path.show'], 'Kelas' => [$courses, 'course.show']] as $heading => [$collection, $routeName])
@if($collection->isNotEmpty())<section class="mt-12"><h2 class="mb-5 text-2xl font-bold">{{ $heading }}</h2><div class="grid gap-4 md:grid-cols-4">@foreach($collection as $item)<a wire:navigate href="{{ route($routeName, $item) }}" class="card hover:border-indigo-500"><h3 class="font-bold">{{ $item->title }}</h3><p class="mt-2 line-clamp-3 text-sm text-slate-600">{{ $item->description }}</p></a>@endforeach</div></section>@endif
@endforeach
@endsection