@extends('public.layout')
@section('seo_title', ($post->seo_title ?: $post->title).' | Besofton Insights')
@section('seo_description', $post->seo_description ?: $post->excerpt ?: \Illuminate\Support\Str::limit($post->content_plain ?: strip_tags($post->content ?? '') ?: $post->title, 155))
@section('canonical', url('/'.$post->slug))
@section('robots', ($preview || $post->noindex) ? 'noindex,nofollow' : 'index,follow')
@section('og_type', 'article')
@section('og_title', $post->og_title ?: $post->seo_title ?: $post->title)
@section('og_description', $post->og_description ?: $post->seo_description ?: $post->excerpt ?: '')
@section('og_image', $post->og_image ?: $post->featured_image ?: '')
@push('head')

@php $crumbs = [['@type'=>'ListItem','position'=>1,'name'=>'Beranda','item'=>route('home')], ['@type'=>'ListItem','position'=>2,'name'=>$post->title,'item'=>url('/'.$post->slug)]]; $breadcrumbSchema = ['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>$crumbs]; @endphp
<script type="application/ld+json">{!! json_encode($breadcrumbSchema, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG) !!}</script>
@php $schema = ['@context'=>'https://schema.org','@type'=>'Article','headline'=>$post->title,'description'=>$post->seo_description ?: $post->excerpt,'datePublished'=>$post->published_at?->toAtomString(),'dateModified'=>$post->updated_at?->toAtomString(),'author'=>['@type'=>'Person','name'=>$post->author?->name ?? 'Tim Besofton'],'publisher'=>['@type'=>'Organization','name'=>'Besofton'],'mainEntityOfPage'=>url('/'.$post->slug)]; @endphp
<script type="application/ld+json">{!! json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG) !!}</script>
@endpush
@section('content')
@if($preview)<div class="mb-6 rounded-lg bg-amber-50 p-4 text-sm font-semibold text-amber-800">Preview privat · halaman ini tidak diindeks.</div>@endif
<nav aria-label="Breadcrumb" class="mb-8 text-sm text-slate-500"><a wire:navigate href="{{ route('home') }}">Beranda</a> / @if($post->category)<a wire:navigate href="{{ route('category.show', $post->category) }}">{{ $post->category->name }}</a> / @endif {{ $post->title }}</nav>
<div id="reading-progress" class="fixed left-0 top-0 z-50 h-1 bg-indigo-600" style="width:0%"></div><article class="mx-auto max-w-3xl"><p class="text-sm font-semibold uppercase tracking-wide text-indigo-700">{{ ucfirst(str_replace('_',' ',$post->content_type)) }}</p><h1 class="mt-3 text-4xl font-extrabold leading-tight md:text-5xl">{{ $post->title }}</h1><p class="mt-5 text-lg text-slate-600">{{ $post->excerpt }}</p><div class="mt-6 flex flex-wrap items-center gap-2 text-sm text-slate-500">Oleh @if($post->author)<a wire:navigate href="{{ route('author.show', $post->author) }}" class="font-semibold text-indigo-700">{{ $post->author->name }}</a>@else Tim Besofton @endif · {{ $post->published_at?->timezone('Asia/Jakarta')->format('d M Y') ?? 'Belum terbit' }} · {{ max(1, ceil(str_word_count($post->content_plain ?? '') / 200)) }} menit baca</div>
@if($post->updated_at && $post->published_at && $post->updated_at->greaterThan($post->published_at->copy()->addDay()))<p class="mt-2 text-sm text-slate-500">Terakhir diperbarui: {{ $post->updated_at->timezone('Asia/Jakarta')->format('d M Y') }}</p>@endif
@if($post->featured_image)<img src="{{ $post->featured_image }}" alt="{{ $post->featured_image_alt ?: $post->title }}" width="1200" height="675" fetchpriority="high" class="mt-8 aspect-video w-full rounded-2xl object-cover">@endif
@auth<form action="{{ route('reader.bookmark', $post) }}" method="post" class="mt-6">@csrf<button class="btn-secondary">Simpan / hapus bookmark</button></form>@endauth
@if($post->direct_answer)<aside class="mt-8 rounded-xl border-l-4 border-indigo-600 bg-indigo-50 p-6"><h2 class="font-bold">Jawaban singkat</h2><p class="mt-2 whitespace-pre-line">{{ $post->direct_answer }}</p></aside>@endif
@if($post->key_takeaways)<aside class="mt-6 rounded-xl bg-slate-50 p-6"><h2 class="font-bold">Inti pembahasan</h2><ul class="mt-3 list-disc space-y-2 pl-5">@foreach(preg_split('/\r?\n/', $post->key_takeaways) as $point)@if(trim($point))<li>{{ trim($point) }}</li>@endif @endforeach</ul></aside>@endif
<nav id="article-toc" aria-label="Daftar isi" class="mt-8 hidden rounded-xl bg-slate-50 p-5"><h2 class="font-bold">Daftar isi</h2><ol class="mt-3 space-y-2 text-sm"></ol></nav>
<div class="article-content mt-10 text-lg leading-relaxed">{!! app(\App\Services\Content\ContentRenderer::class)->render($post->content) !!}</div>
@if($post->summary)<section class="mt-10 rounded-xl bg-slate-50 p-6"><h2 class="text-xl font-bold">Ringkasan</h2><p class="mt-3 whitespace-pre-line">{{ $post->summary }}</p></section>@endif
@if($post->sources->isNotEmpty())<section class="mt-10"><h2 class="text-xl font-bold">Referensi</h2><ol class="mt-4 list-decimal space-y-2 pl-5 text-sm">@foreach($post->sources as $source)<li><a href="{{ $source->url }}" target="_blank" rel="noopener noreferrer" class="text-indigo-700 underline">{{ $source->title }}</a>@if($source->publisher) · {{ $source->publisher }} @endif</li>@endforeach</ol></section>@endif
@if($post->tags->isNotEmpty())<div class="mt-10 flex flex-wrap gap-2">@foreach($post->tags as $tag)<a wire:navigate href="{{ route('tag.show', $tag) }}" class="rounded-full bg-slate-100 px-3 py-1 text-sm hover:bg-indigo-100">#{{ $tag->name }}</a>@endforeach</div>@endif
@if(!$preview)<form class="mt-12 rounded-xl bg-slate-50 p-5" action="{{ route('post.feedback', $post) }}" method="post">@csrf<p class="font-semibold">Apakah artikel ini membantu?</p><div class="mt-3 flex gap-2"><button name="helpful" value="1" class="btn-secondary">Ya</button><button name="helpful" value="0" class="btn-secondary">Belum</button></div></form>@endif
<div class="mt-8 flex gap-3 text-sm"><a href="https://wa.me/?text={{ urlencode($post->title.' '.url('/'.$post->slug)) }}" target="_blank" rel="noopener noreferrer" class="text-indigo-700">Bagikan</a><button type="button" data-copy="{{ url('/'.$post->slug) }}" class="text-indigo-700">Salin tautan</button></div></article>
@if(!$preview)<section class="mx-auto mt-14 max-w-3xl"><h2 class="text-2xl font-bold">Tanya jawab</h2><p class="mt-2 text-sm text-slate-600">Pertanyaan ditinjau sebelum tampil.</p><form action="{{ route('post.question', $post) }}" method="post" class="mt-6 space-y-3 rounded-xl bg-slate-50 p-5">@csrf @guest<div class="grid gap-3 sm:grid-cols-2"><input class="form-input" name="name" placeholder="Nama" required value="{{ old('name') }}"><input class="form-input" name="email" type="email" placeholder="Email" required value="{{ old('email') }}"></div>@endguest<textarea class="form-input" name="body" required minlength="10" maxlength="2000" rows="4" placeholder="Tulis pertanyaan Anda...">{{ old('body') }}</textarea>@error('body')<p class="error">{{ $message }}</p>@enderror<button class="btn-primary">Kirim pertanyaan</button></form><div class="mt-7 space-y-4">@foreach($questions as $question)<div class="rounded-xl border border-slate-200 p-5"><p class="font-semibold">{{ $question->name }}</p><p class="mt-2 whitespace-pre-line">{{ $question->body }}</p>@foreach($question->answers as $answer)<div class="mt-4 rounded-lg bg-indigo-50 p-4"><p class="text-xs font-semibold text-indigo-800">Jawaban {{ $answer->user?->name ?? 'Tim Besofton' }}</p><p class="mt-2 whitespace-pre-line">{{ $answer->body }}</p></div>@endforeach</div>@endforeach</div></section>@endif
@if($related->isNotEmpty())<section class="mt-16"><h2 class="mb-5 text-2xl font-bold">Baca selanjutnya</h2><div class="grid gap-5 md:grid-cols-3">@foreach($related as $post)@include('public.partials.card', ['post'=>$post])@endforeach</div></section>@endif
@endsection