@extends('admin.layout')
@section('title', $post->exists ? 'Edit Artikel' : 'Buat Artikel')
@section('content')
<div class="mb-6"><a wire:navigate href="{{ route('admin.posts.index') }}" class="text-sm text-indigo-700">← Kembali ke artikel</a><h1 class="mt-2 text-3xl font-bold">{{ $post->exists ? 'Edit artikel' : 'Buat artikel' }}</h1></div>
@if($errors->any())<div class="mb-5 rounded-lg bg-red-50 p-4 text-sm text-red-800">Periksa kembali isian formulir.</div>@endif
<div class="admin-post-layout">
<form method="post" action="{{ $post->exists ? route('admin.posts.update', $post) : route('admin.posts.store') }}" class="admin-post-form" data-post-form>@csrf @if($post->exists) @method('PATCH') @endif
<div class="admin-post-main space-y-6"><section class="card space-y-5"><div><label class="form-label" for="title">Judul *</label><input class="form-input" id="title" name="title" required maxlength="191" value="{{ old('title', $post->title) }}" data-slug-source>@error('title')<p class="error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="slug">Slug</label><input class="form-input" id="slug" name="slug" value="{{ old('slug', $post->slug) }}" data-slug-target>@error('slug')<p class="error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="excerpt">Ringkasan</label><textarea class="form-input" id="excerpt" name="excerpt" rows="3">{{ old('excerpt', $post->excerpt) }}</textarea>@error('excerpt')<p class="error">{{ $message }}</p>@enderror</div>@include('admin.posts.editor')</section>
<section class="card space-y-4"><h2 class="text-lg font-semibold">Ringkasan & jawaban langsung</h2><div><label class="form-label">Direct answer</label><textarea class="form-input" name="direct_answer" rows="3">{{ old('direct_answer', $post->direct_answer) }}</textarea></div><div><label class="form-label">Key takeaways (satu poin per baris)</label><textarea class="form-input" name="key_takeaways" rows="4">{{ old('key_takeaways', $post->key_takeaways) }}</textarea></div><div><label class="form-label">Ringkasan</label><textarea class="form-input" name="summary" rows="4">{{ old('summary', $post->summary) }}</textarea></div></section>
<section class="card space-y-4"><h2 class="text-lg font-semibold">SEO</h2><div><label class="form-label" for="focus-keyphrase">Focus Keyphrase</label><input class="form-input" id="focus-keyphrase" name="focus_keyphrase" maxlength="191" placeholder="Contoh: prompt AI untuk coding" value="{{ old('focus_keyphrase', $post->focus_keyphrase) }}"><p class="mt-1 text-xs text-slate-500">Kata atau frasa utama yang ingin ditargetkan artikel ini.</p>@error('focus_keyphrase')<p class="error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="seo-title">Judul SEO</label><input class="form-input" id="seo-title" name="seo_title" value="{{ old('seo_title', $post->seo_title) }}"><p class="mt-1 text-xs text-slate-500" data-seo-title-meter></p></div><div><label class="form-label" for="seo-description">Deskripsi SEO</label><textarea class="form-input" id="seo-description" name="seo_description" rows="3">{{ old('seo_description', $post->seo_description) }}</textarea><p class="mt-1 text-xs text-slate-500" data-seo-description-meter></p></div><div><label class="form-label">OG title</label><input class="form-input" name="og_title" value="{{ old('og_title', $post->og_title) }}"></div><div><label class="form-label">OG description</label><textarea class="form-input" name="og_description" rows="2">{{ old('og_description', $post->og_description) }}</textarea></div>@include('admin.posts.og-field')<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="noindex" value="1" @checked(old('noindex', $post->noindex))> Jangan index halaman ini</label></section>
<section class="card space-y-4"><h2 class="text-lg font-semibold">Publikasi</h2><div><label class="form-label">Status *</label><select class="form-input" name="status">@foreach((auth()->user()->cannot('articles.publish') ? ['draft','pending_review'] : ['draft','pending_review','scheduled','published','archived']) as $status)<option value="{{ $status }}" @selected(old('status', $post->status ?: 'draft') === $status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></div><div><label class="form-label">Jadwal (bila terjadwal)</label><input class="form-input" type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at', $post->scheduled_at?->format('Y-m-d\TH:i')) }}">@error('scheduled_at')<p class="error">{{ $message }}</p>@enderror</div><div><label class="form-label">Jenis konten</label><select class="form-input" name="content_type">@foreach(['article','tutorial','guide','news','opinion','case_study','video_article'] as $type)<option value="{{ $type }}" @selected(old('content_type', $post->content_type ?: 'article') === $type)>{{ ucfirst(str_replace('_',' ',$type)) }}</option>@endforeach</select></div><div><label class="form-label">Tingkat</label><select class="form-input" name="difficulty"><option value="">—</option>@foreach(['beginner','intermediate','advanced'] as $difficulty)<option value="{{ $difficulty }}" @selected(old('difficulty', $post->difficulty) === $difficulty)>{{ ucfirst($difficulty) }}</option>@endforeach</select></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $post->is_featured))> Artikel unggulan</label></section>
@include('admin.posts.taxonomy-section')
@include('admin.posts.references')
<section class="card space-y-4"><h2 class="text-lg font-semibold">Gambar artikel</h2>@include('admin.posts.image-field', ['kind' => 'featured'])<div><label class="form-label" for="featured-image-alt">Alt text</label><input class="form-input" id="featured-image-alt" name="featured_image_alt" maxlength="191" value="{{ old('featured_image_alt', $post->featured_image_alt) }}"><p class="mt-1 text-xs text-slate-500">Jelaskan isi gambar secara singkat untuk aksesibilitas dan SEO.</p>@error('featured_image_alt')<p class="error">{{ $message }}</p>@enderror</div></section>
@php $checks = ['Judul tersedia' => filled($post->title), 'Slug valid' => filled($post->slug), 'Ringkasan / meta tersedia' => filled($post->seo_description ?: $post->excerpt), 'Penulis tersedia' => filled($post->author_id), 'Gambar unggulan tersedia' => filled($post->featured_image), 'Alt gambar tersedia' => filled($post->featured_image_alt), 'Artikel terkait tersedia' => $post->exists && $post->relatedPosts->isNotEmpty(), 'Referensi tersedia' => $post->exists && $post->sources()->exists(), 'Konten substantif' => mb_strlen($post->content_plain ?? '') >= 300]; @endphp
<section class="card"><h2 class="text-lg font-semibold">Checklist konten</h2><ul class="mt-3 space-y-2 text-sm">@foreach($checks as $label => $complete)<li class="{{ $complete ? 'text-green-700' : 'text-amber-700' }}">{{ $complete ? '✓' : '•' }} {{ $label }}</li>@endforeach</ul><p class="mt-3 text-xs text-slate-500">Berdasarkan konten yang terakhir disimpan.</p></section>
</div>
@include('admin.posts.seo-analysis')
<div class="admin-post-actions sticky bottom-3 flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-lg"><button class="btn-primary">{{ $post->exists ? 'Simpan perubahan' : 'Buat artikel' }}</button><a wire:navigate href="{{ route('admin.posts.index') }}" class="btn-secondary">Batal</a>@if($post->exists)<a wire:navigate href="{{ route('admin.posts.preview', $post) }}" class="btn-secondary">Preview</a><a wire:navigate href="{{ route('admin.posts.revisions', $post) }}" class="btn-secondary">Revisi</a><a wire:navigate href="{{ route('admin.posts.sources.index', $post) }}" class="btn-secondary">Referensi</a>@endif</div>
</form>
</div>
@include('admin.posts.taxonomy-dialog')
@include('admin.posts.image-picker-dialog')
@endsection
