@extends('admin.layout')
@section('title', 'Artikel')
@section('content')
<div class="mb-6 flex items-center justify-between gap-3"><div><h1 class="text-3xl font-bold">Artikel</h1><p class="text-sm text-slate-500">Kelola artikel dan alur editorial.</p></div><a wire:navigate href="{{ route('admin.posts.create') }}" class="btn-primary">+ Buat artikel</a></div>
<form action="{{ route('admin.posts.index') }}" method="get" class="card mb-5 grid gap-3 md:grid-cols-5"><input name="q" value="{{ request('q') }}" placeholder="Cari artikel..." class="form-input md:col-span-2"><select name="status" class="form-input"><option value="">Semua status</option>@foreach(['draft','pending_review','scheduled','published','archived'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select><select name="category" class="form-input"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category') == $category->id)>{{ $category->name }}</option>@endforeach</select><div class="flex gap-2"><button class="btn-primary">Filter</button><a wire:navigate href="{{ route('admin.posts.index') }}" class="btn-secondary">Reset</a></div><div class="md:col-span-5 text-sm"><a wire:navigate href="{{ route('admin.posts.index', ['trash'=>1]) }}" class="text-indigo-700 hover:underline">Lihat Trash</a></div></form>
<div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table class="w-full min-w-[750px] text-left text-sm"><thead class="bg-slate-100 text-slate-500"><tr><th class="p-4">Judul</th><th class="p-4">Kategori</th><th class="p-4">Status</th><th class="p-4">Tanggal</th><th class="p-4">Aksi</th></tr></thead><tbody>
@forelse($posts as $post)<tr class="border-t border-slate-100"><td class="p-4"><a wire:navigate href="{{ route('admin.posts.edit', $post) }}" class="font-semibold text-indigo-800 hover:underline">{{ $post->title }}</a><div class="text-xs text-slate-500">/{{ $post->slug }}</div></td><td class="p-4">{{ $post->category?->name ?? '—' }}</td><td class="p-4"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs">{{ str_replace('_', ' ', $post->status) }}</span></td><td class="p-4">{{ $post->published_at?->timezone('Asia/Jakarta')->format('d M Y') ?? $post->created_at->timezone('Asia/Jakarta')->format('d M Y') }}</td><td class="p-4"><div class="flex gap-3">@if($post->trashed())<form action="{{ route('admin.posts.restore', $post->id) }}" method="post">@csrf<button class="text-indigo-700">Pulihkan</button></form>@can('forceDelete', $post)<form action="{{ route('admin.posts.force', $post->id) }}" method="post" data-confirm="Hapus permanen artikel ini?">@csrf @method('DELETE')<button class="text-red-700">Hapus permanen</button></form>@endcan @else<a wire:navigate href="{{ route('admin.posts.edit', $post) }}" class="text-indigo-700">Edit</a><form action="{{ route('admin.posts.destroy', $post) }}" method="post" data-confirm="Pindahkan artikel ini ke Trash?">@csrf @method('DELETE')<button class="text-red-700">Hapus</button></form>@endif</div></td></tr>
@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">Belum ada artikel. <a wire:navigate href="{{ route('admin.posts.create') }}" class="text-indigo-700 underline">Buat artikel pertama</a>.</td></tr>@endforelse
</tbody></table></div><div class="mt-5">{{ $posts->links() }}</div>
@endsection